# Generated by Django 3.2.4 on 2021-06-05 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('home_phone', models.CharField(max_length=12)),
                ('work_phone', models.CharField(max_length=12)),
                ('cell_phone', models.CharField(max_length=12)),
                ('addr_line1', models.CharField(max_length=200)),
                ('addr_line2', models.CharField(max_length=200)),
                ('addr_line3', models.CharField(max_length=200)),
                ('addr_line4', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=50)),
            ],
        ),
    ]
