# Generated by Django 3.2.4 on 2021-06-05 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='addr_line2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='customers',
            name='addr_line3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='customers',
            name='addr_line4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='customers',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='customers',
            name='home_phone',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='customers',
            name='work_phone',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
